import type { ContentItem, Workspace } from "./types";

export const DEMO_WORKSPACE: Workspace = {
  id: "workspace_calio_demo",
  name: "Northstar Studio",
  slug: "northstar-studio",
};

export const DEMO_CONTENT: ContentItem[] = [
  {
    id: "content_01",
    title: "Why consistency beats virality",
    summary: "A practical take on building a content habit that compounds.",
    publishDate: "2026-08-03",
    status: "published",
    format: "Carousel",
    platforms: ["Instagram", "LinkedIn"],
    pillar: "Creator systems",
    hook: "One viral post will not build the system your business needs.",
    caption: "Consistency is less exciting than virality—and far more useful.",
    productionNotes: "Use the notebook photography from the July brand shoot.",
  },
  {
    id: "content_02",
    title: "Behind the rebrand",
    summary: "Walk through three decisions that changed the visual system.",
    publishDate: "2026-08-06",
    status: "published",
    format: "Reel",
    platforms: ["Instagram", "TikTok"],
    pillar: "Behind the scenes",
    hook: "The best part of this rebrand is the detail nobody will notice.",
    caption: "A brand system should make the next decision easier.",
    productionNotes: "Screen recording, studio b-roll, captions burned in.",
  },
  {
    id: "content_03",
    title: "The two-hour content sprint",
    summary: "A repeatable workflow for planning a full week in one sitting.",
    publishDate: "2026-08-11",
    status: "scheduled",
    format: "Newsletter",
    platforms: ["Newsletter"],
    pillar: "Creator systems",
    hook: "Your content calendar does not need another planning meeting.",
    caption: "This is the exact sprint we use every Monday.",
    productionNotes: "Add downloadable checklist before final review.",
  },
  {
    id: "content_04",
    title: "Stop opening with your credentials",
    summary: "Rewrite weak introductions around the audience problem.",
    publishDate: "2026-08-13",
    status: "review",
    format: "Post",
    platforms: ["LinkedIn"],
    pillar: "Writing craft",
    hook: "Your audience does not need your résumé in the first sentence.",
    caption: "Lead with tension. Earn the introduction later.",
    productionNotes: "Needs final example and proofread.",
  },
  {
    id: "content_05",
    title: "Studio desk reset",
    summary: "A tactile, low-dialogue process video for the new workspace.",
    publishDate: "2026-08-17",
    status: "drafting",
    format: "Reel",
    platforms: ["Instagram", "TikTok"],
    pillar: "Behind the scenes",
    hook: "Reset the space, reset the work.",
    caption: "A quieter studio for a sharper season.",
    productionNotes: "Morning light. Keep cuts slow and sound-led.",
  },
  {
    id: "content_06",
    title: "Five prompts for a stronger point of view",
    summary: "A saveable prompt set for creators stuck in safe ideas.",
    publishDate: "2026-08-20",
    status: "drafting",
    format: "Carousel",
    platforms: ["Instagram", "LinkedIn"],
    pillar: "Writing craft",
    hook: "Useful content answers questions. Memorable content takes a position.",
    caption: "Borrow these prompts before your next planning session.",
    productionNotes: "Design as five numbered editorial cards.",
  },
  {
    id: "content_07",
    title: "What we learned from 30 days of publishing",
    summary: "Turn the monthly review into a transparent learning post.",
    publishDate: "2026-08-25",
    status: "idea",
    format: "Post",
    platforms: ["LinkedIn"],
    pillar: "Build in public",
    hook: "Thirty days, twenty posts, and one assumption we got completely wrong.",
    caption: "The honest version of our first month publishing consistently.",
    productionNotes: "Pull reach and save-rate numbers before drafting.",
  },
  {
    id: "content_08",
    title: "September campaign teaser",
    summary: "Introduce the next campaign without revealing the full concept.",
    publishDate: "2026-08-28",
    status: "idea",
    format: "Story",
    platforms: ["Instagram"],
    pillar: "Campaigns",
    hook: "Something new is taking shape.",
    caption: "September, seen differently.",
    productionNotes: "Three frames. Macro details only.",
  },
];
